name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7

      - name: Get Version
        run: echo "MYPYPI_VERSION=$(poetry version --short)" >> $GITHUB_ENV

      - name: Export requirements
        run: poetry export -o requirements.txt

      - name: Dockerhub Login
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Github CR Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: nthnv.me CR Login
        uses: docker/login-action@v1
        with:
          registry: cr.nthnv.me
          username: ${{ secrets.NTHNVCR_USERNAME }}
          password: ${{ secrets.NTHNVCR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            docker.io/nathanvaughn/mypypi:latest
            docker.io/nathanvaughn/mypypi:${{ env.MYPYPI_VERSION }}
            ghcr.io/nathanvaughn/mypypi:latest
            ghcr.io/nathanvaughn/mypypi:${{ env.MYPYPI_VERSION }}
            cr.nthnv.me/library/mypypi:latest
            cr.nthnv.me/library/mypypi:${{ env.MYPYPI_VERSION }}
